name: Yarn CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Setup Yarn
      uses: Borales/actions-yarn@master
      with:
        version: 10.x
    - name: yarn install & lint
      run: |
        yarn install
        yarn lint
    
    - name: Build Release
      if: github.branch == 'master'
      run: |
        yarn dist
        
    - name: GH Pages Publish
      uses: maxheld83/ghpages@v0.2.1
      if: github.branch == 'master'
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        BUILD_DIR: "dist/"
